Add Dockerfile
hashbang/userdb pull request #34
Opened 2019-01-07 13:45 UTC by daurnimator

This PR adds a dockerfile so that userdb can be installed using a kubernetes job.

2019-01-08 20:12 UTC, drGrove commented
Should we get ignoring any files? I'd assume we'd want to ignore .git at the minimum

2019-01-09 02:47 UTC, daurnimator commented
> Should we get ignoring any files? I'd assume we'd want to ignore .git at the minimum

Good idea; should add a .dockerignore file in this PR.

2019-04-15 00:38 UTC, drGrove commented
@daurnimator please add a `.dockerignore` to this PR.

2019-04-15 00:41 UTC, drGrove requested changes

2019-04-15 00:41 UTC, drGrove commented on Dockerfile
> +RUN apk --no-cache add make postgresql-client
After installing create a new user and drop into that user.

2019-04-15 00:41 UTC, drGrove commented on Dockerfile
> +ADD . /userdb
Change this to:
```
COPY --chown=<user>:<user> . /home/<user>/userdb
```

2019-04-15 00:41 UTC, drGrove commented on Dockerfile
> +COPY --from=gen_schemas /userdb/json-schemas.sql.tmp /userdb/json-schemas.sql.tmp
Update path as per above

2019-04-15 00:41 UTC, drGrove commented on Dockerfile
> +WORKDIR  /userdb
When you drop into the user, you can set the workdir there. Moving this unchanging layer higher up

2019-04-15 01:20 UTC, drGrove commented on Dockerfile
> +RUN apk --no-cache add make postgresql-client
Pin version so multiple builds can be verified

2019-04-15 01:21 UTC, drGrove commented on Dockerfile
> +FROM alpine:latest
Avoid using latest.

2019-04-15 01:36 UTC, drGrove commented on Dockerfile
> +RUN pip install --no-cache-dir PyYAML
Pin version of PyYAML

2020-01-18 09:41 UTC, lrvick commented
this pr is deprecated by my lrvick-refactor branch which was based on these commits.

2020-01-18 09:41 UTC, closed without merging