nss: add schema for nss-pgsql
hashbang/userdb pull request #41
Opened 2019-12-16 14:46 UTC by daurnimator

Untested. Created to expose tables for usage by [libnss_pgsql](http://pgfoundry.org/projects/sysauth/)

2019-12-17 02:50 UTC, benharri approved these changes

2019-12-17 14:39 UTC, RyanSquared commented
Does this require a role to be created? I'm confused on what `grant select on nss_pgsql.groupmember to nss_pgsql;` does otherwise.

2019-12-17 15:07 UTC, RyanSquared requested changes

2019-12-17 15:07 UTC, RyanSquared commented on nss.sql
> +grant select on nss_pgsql.groupmember to nss_pgsql;
Would like to know what `to nss_pgsql` means as I assume it means a role, which AFAICT we do not create right now?

2019-12-18 01:01 UTC, daurnimator commented
> Does this require a role to be created?

yes.
I did it by hand on production, but yes it should get added to this PR.

2020-01-18 09:38 UTC, lrvick commented
I need all the code in for the refactor so I am merging this. Hopefully we can figure out the role thing.

2020-01-18 09:39 UTC, merged